language: rust
rust:
- nightly
os:
- linux
cache:
  cargo: true
  directories:
  - "$HOME/deps"
branches:
  only:
    - testing
    - master
script:
- cd $TRAVIS_BUILD_DIR
- cargo build
- cargo test
after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=flight/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: AibVJc5P2ucUeONGW572feS4+wv758Y5cqZp30lNbgEnVTzaiD1jGWofGfpTJivESfNoD+mKC8eIe9LMrxtgaF1fRw+icnIktlzFqtbu4RCz2eX7H4IV4zi8auo9T5iu/xRCQLB5uFj0zSPdvjsVcXP0tm2ehyhxlUWAJrK6QlPUUReAbI99yTt0hYLsgG1Mbl+0lZpJHgnzinI1NSPZpP1LWEeO6EZYxYBCTMzULSDj7MrBe7ys+FfQ0+2t97n7nhdV9wuuE89S/KW278SrK4iaEZwJnDCI68yxIgNwlDLazyXvTS2+s6o2E3evorcIAJTt3PVbQCmpu5NWQeho+sTeO+UH6eH5DhPW9Thcj15FqEvO0v5weX/FQzndPftqIKGppbOFnaAVdPprl5myF4D3yjxkBMRqZbRgEzexeKzPK2h/TDmmM/mv+jOYx/dWiMq5euRpiAsS09YnP0uKwO15YbXj9O8AV6A/ZAPYWCylo1yUC6OZq6Aem5jZ3W/4OKPIGXLmVVxUdsScrYZ4TfP3NRVwl2JrFrE7B/j0CSUATYZIA6oHGwRw3qSm6/tP4YzO3iCU2zvsoEATZffAgMF8b9t7QbUwX75cyoOkFXsdOCZRAM/BZ4GWLPLqNqedO1boV2S2I4IMmkDGNJzOS5VlqwtzsyVrjoaSjxnr/IQ=
